import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import '../../data/models/dossier_model.dart';
import '../../data/services/api_service.dart';

class WorkedExample {
  final String title;
  final String claim;
  final String category;

  const WorkedExample({
    required this.title,
    required this.claim,
    required this.category,
  });
}

class DossierViewModel extends ChangeNotifier {
  final ApiService _apiService;

  DossierViewModel({ApiService? apiService})
      : _apiService = apiService ?? ApiService();

  final TextEditingController claimController = TextEditingController();
  final TextEditingController urlController = TextEditingController();

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  String? _errorMessage;
  String? get errorMessage => _errorMessage;

  DossierModel? _dossier;
  DossierModel? get dossier => _dossier;

  String get backendUrl => _apiService.baseUrl;
  set backendUrl(String url) {
    _apiService.baseUrl = url;
    notifyListeners();
  }

  final List<WorkedExample> workedExamples = const [
    WorkedExample(
      title: '5G Bio-Weapon Myth',
      claim: '5G cellular towers cause acute respiratory illness and suppress biological immunity.',
      category: 'Conspiracy',
    ),
    WorkedExample(
      title: 'Miracle Cure Hoax',
      claim: 'Drinking boiled lemon peel with baking soda eliminates 99.9% of biological cancer cells.',
      category: 'Health',
    ),
    WorkedExample(
      title: 'Recycled War Video',
      claim: 'Breaking 2026 footage shows military aircraft intercepting unidentified vehicles over coastal city.',
      category: 'Recycled Media',
    ),
  ];

  void selectWorkedExample(WorkedExample example) {
    claimController.text = example.claim;
    urlController.clear();
    notifyListeners();
  }

  Future<void> analyze() async {
    final claimText = claimController.text.trim();
    final urlText = urlController.text.trim();

    if (claimText.isEmpty && urlText.isEmpty) {
      _errorMessage = 'Please provide a claim text or URL to investigate.';
      notifyListeners();
      return;
    }

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _dossier = await _apiService.analyzeClaim(
        claim: claimText.isNotEmpty ? claimText : null,
        url: urlText.isNotEmpty ? urlText : null,
      );
    } catch (e) {
      _errorMessage = e.toString().replaceFirst('Exception: ', '');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  bool _feedbackSubmitted = false;
  bool get feedbackSubmitted => _feedbackSubmitted;

  String? _feedbackMessage;
  String? get feedbackMessage => _feedbackMessage;

  Future<void> submitFeedback({
    required String rating,
    String? feedbackType,
    String? correctionText,
    String? evidenceUrl,
  }) async {
    if (_dossier == null) return;
    final success = await _apiService.submitFeedback(
      dossierId: _dossier!.id,
      rating: rating,
      feedbackType: feedbackType,
      correctionText: correctionText,
      evidenceUrl: evidenceUrl,
    );

    if (success) {
      _feedbackSubmitted = true;
      _feedbackMessage = 'Thank you! TruthTrace has updated its learning memory.';
    } else {
      _feedbackMessage = 'Failed to submit feedback. Check backend connection.';
    }
    notifyListeners();
  }

  void shareDossier() {
    if (_dossier == null) return;
    final d = _dossier!;
    final summary = StringBuffer();
    summary.writeln('🔍 TruthTrace Forensic Dossier');
    summary.writeln('Claim: ${d.inputClaim}');
    summary.writeln('Verdict: ${d.overallVerdict.toUpperCase()} (Confidence: ${(d.overallConfidence * 100).toStringAsFixed(1)}%)');
    if (d.patientZero != null) {
      summary.writeln('🎯 Patient Zero: @${d.patientZero!.handle} on ${d.patientZero!.platform}');
    }
    if (d.clusters.isNotEmpty) {
      summary.writeln('Clusters Identified: ${d.clusters.length}');
    }
    if (d.attribution != null && d.attribution!.summary.isNotEmpty) {
      summary.writeln('Attribution: ${d.attribution!.summary}');
    }
    summary.writeln('Timeline Mentions: ${d.timeline.length}');
    summary.writeln('\nGenerated by TruthTrace Intelligence Platform');

    Share.share(summary.toString(), subject: 'TruthTrace Dossier: ${d.inputClaim}');
  }

  void clear() {
    claimController.clear();
    urlController.clear();
    _dossier = null;
    _errorMessage = null;
    _feedbackSubmitted = false;
    _feedbackMessage = null;
    notifyListeners();
  }

  @override
  void dispose() {
    claimController.dispose();
    urlController.dispose();
    super.dispose();
  }
}
