import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import '../../data/models/dossier_model.dart';
import '../../data/services/api_service.dart';

class DossierViewModel extends ChangeNotifier {
  final ApiService _apiService;

  DossierViewModel({ApiService? apiService})
      : _apiService = apiService ?? ApiService();

  final TextEditingController claimController = TextEditingController();
  final TextEditingController urlController = TextEditingController();

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  String? _errorMessage;
  String? get errorMessage => _errorMessage;

  DossierModel? _dossier;
  DossierModel? get dossier => _dossier;

  String get backendUrl => _apiService.baseUrl;
  set backendUrl(String url) {
    _apiService.baseUrl = url;
    notifyListeners();
  }

  final List<String> sampleClaims = [
    "Drinking warm salt water daily reverses biological aging within 30 days.",
    "Government passes emergency bill to ban all consumer coffee imports.",
    "Scientists discover intact dinosaur DNA inside amber preserved in Antarctica.",
  ];

  void selectSample(String sample) {
    claimController.text = sample;
    urlController.clear();
    notifyListeners();
  }

  Future<void> analyze() async {
    final claimText = claimController.text.trim();
    final urlText = urlController.text.trim();

    if (claimText.isEmpty && urlText.isEmpty) {
      _errorMessage = 'Please provide a claim text or URL to investigate.';
      notifyListeners();
      return;
    }

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _dossier = await _apiService.analyzeClaim(
        claim: claimText.isNotEmpty ? claimText : null,
        url: urlText.isNotEmpty ? urlText : null,
      );
    } catch (e) {
      _errorMessage = e.toString().replaceFirst('Exception: ', '');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  void shareDossier() {
    if (_dossier == null) return;
    final d = _dossier!;
    final summary = StringBuffer();
    summary.writeln('🔍 TruthTrace Forensic Dossier');
    summary.writeln('Claim: ${d.inputClaim}');
    summary.writeln('Verdict: ${d.overallVerdict.toUpperCase()} (Confidence: ${(d.overallConfidence * 100).toStringAsFixed(1)}%)');
    if (d.patientZero != null) {
      summary.writeln('🎯 Patient Zero: @${d.patientZero!.handle} on ${d.patientZero!.platform}');
    }
    summary.writeln('Timeline Events Discovered: ${d.timeline.length}');
    summary.writeln('\nGenerated by TruthTrace Intelligence Platform');

    Share.share(summary.toString(), subject: 'TruthTrace Dossier: ${d.inputClaim}');
  }

  void clear() {
    claimController.clear();
    urlController.clear();
    _dossier = null;
    _errorMessage = null;
    notifyListeners();
  }

  @override
  void dispose() {
    claimController.dispose();
    urlController.dispose();
    super.dispose();
  }
}
